### ISSUE TITLE
Possible contributions to Annotated Bibliography

### ISSUE THREAD

**Issue by btusdin** [markupdeclaration/markupdeclaration.org#22]
We might want to point to collections of markup-related content as well as specific articles, books, etc.   If that seems appealing, perhaps we could start with this: 
<section id="collections">
    <h1>Collections of Markup-related Materials</h1>
 
  
    <div class="bib-entry">
      <h2 class="sort-name">Cover Pages</h2>
      <h3 class="ref-title">The Cover Pages at OASIS</h3>
      <p class="ref-location"><a href="http://xml.coverpages.org/index.html">http://xml.coverpages.org/index.html</a></p>
      <div class="annotation">
        <p>Frozen in 2010, the Cover Pages are a detailed record of the development of SGML and XML, including descriptions of events, products, and specifications. Many of the links still work; the value of this enormous resource will fade over time but as of 2018 it is still a treasure trove.</p>
        <p class="sig">annotated by: B. T. Usdin</p>
      </div>
    </div>
  
  
    <div class="bib-entry">
      <h2 class="sort-name">Extreme Markup Languages, Proceedings</h2>
      <h3 class="ref-title">Proceedings of Extreme Markup Languages 2001 - 2007</h3>
      <p class="ref-location"><a href="http://conferences.idealliance.org/extreme/index.html">http://conferences.idealliance.org/extreme/index.html</a></p>
      <div class="annotation">
        <p>Extreme Markup Languages was a conference series devoted to Markup Languages, including but not limited to SGML and XML. Many people consider it the predecessor to "Balisage: The Markup Conference".</p>
        <p class="sig">annotated by: B. T. Usdin</p>
      </div>
    </div> 
 

    <div class="bib-entry">
      <h2 class="sort-name">JATS-Con proceedings</h2>
      <h3 class="ref-title">JATS-Con conference proceedings</h3>
      <p class="ref-location"><a href="https://www.ncbi.nlm.nih.gov/books/NBK65129/">https://www.ncbi.nlm.nih.gov/books/NBK65129/</a></p>
      <div class="annotation">
        <p>Starting in 2010, JATS-Con is a (mostly) annual event about the Journal Article Tag Suite and related XML vocabularies. The proceedings include formal articles, slides, and videos of presentations. </p>
        <p class="sig">annotated by: B. T. Usdin</p>
      </div>
    </div>

    <div class="bib-entry">
      <h2 class="sort-name">XML.com</h2>
      <h3 class="ref-title">“XML.com” by Textuality</h3>
      <p class="ref-location"><a href="https://www.xml.com/">https://www.xml.com/</a></p>
      <div class="annotation">
        <p>XML.com contains curated information aimed at professionals in fields where XML is widely used.  These include publishing (for example, technical documentation and technical publishing) and healthcare (for example, HL7 and related work).</p>
        <p class="sig">from the site</p>
      </div>
    </div> 

    <div class="bib-entry">
      <h2 class="sort-name">XML London, Proceedings</h2>
      <h3 class="ref-title">Proceedings of the XML London conference</h3>
      <p class="ref-location">2016 <a href="http://xmllondon.com/2016/xmllondon-2016-proceedings.pdf">http://xmllondon.com/2016/xmllondon-2016-proceedings.pdf</a></p>
      <p class="ref-location">2015 <a href="http://xmllondon.com/2015/xmllondon-2015-proceedings.pdf">http://xmllondon.com/2015/xmllondon-2015-proceedings.pdf</a></p>
      <p class="ref-location">2014 <a href="http://xmllondon.com/2014/xmllondon-2014-proceedings.pdf">http://xmllondon.com/2014/xmllondon-2014-proceedings.pdf</a></p>
      <p class="ref-location">2013 <a href="http://xmllondon.com/2013/xmllondon-2013-proceedings.pdf">http://xmllondon.com/2013/xmllondon-2013-proceedings.pdf</a></p>
      <div class="annotation">
        <p>A 2 day conference for XML, Linked Data and W3C technology users to discuss their experiences while discovering the latest innovations and what others are doing in the industry.</p>
        <p class="sig">annotated from the conference web site</p>
      </div>
    </div>

    <div class="bib-entry">
      <h2 class="sort-name">XML Prague, Proceedings</h2>
      <h3 class="ref-title">XML Prague Archive</h3>
      <p class="ref-location"><a href="http://www.xmlprague.cz/archive/">http://www.xmlprague.cz/archive/</a></p>
      <div class="annotation">
        <p>Sessions and posters from XML Prague starting in 2005 include PDF of the proceedings and video of presentations starting in 2007.</p>
        <p class="sig">annotated from the conference web site</p>
      </div>
    </div>

  </section>

**Comment by ndw** [comment]
We did this. I should have mentioned it in the PR. It was #25
