### ISSUE TITLE
stutter in display of bibliography introduction

### ISSUE THREAD

**Issue by btusdin** [markupdeclaration/markupdeclaration.org#23]
The introduction to the annotated bibliography appears to start with: 
  "This list list of works about ..." which is pretty clunky. I think the duplicate "list" has something to do with the link to the contribution instructions, but I can't see how and I don't see how to fix it. (This HTML stuff can be complicated!)

**Comment by btusdin** [comment]
I am confused. The new entries are there, but the … list list … (which I thought Bethan had fixed) is also still there. 





This was supposed to be easy. 

— Tommie

Don’t mind my grumbling - it has been a long difficult day highlighted by an allergist drawing a grid on my arm and poking small amounts of flu vaccine and control substances into me in an itchy pattern. Grumble! 




> On Oct 22, 2018, at 6:19 PM, Norman Walsh <notifications@github.com> wrote:
> 
> Closed #23 via #26.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

====================================================================== 
B. Tommie Usdin                        mailto:btusdin@mulberrytech.com
Mulberry Technologies, Inc.               https://www.mulberrytech.com
17 West Jefferson Street                           Phone: 301/315-9631 
Suite 207                                    Direct Line: 301/315-9634 
Rockville, MD  20850                                 Fax: 301/315-8285 
----------------------------------------------------------------------
Mulberry Technologies: A Consultancy Specializing in XML and SGML               
======================================================================

**Comment by ndw** [comment]
Apologies for the confusion. The fixes are definitely in the repository. My guess is that GitHub is still processing a long backlog of updates. If it's not fixed by tomorrow, or whenever GitHub claims victory, I'll take a closer look.

**Comment by btusdin** [comment]
It looks like it all worked! 

I am encouraged and will see what I can do to stir up interest. (I may start by coaxing Debbie to tweet about the annotated bibliography!)

— Tommie


> On Oct 22, 2018, at 6:32 PM, Norman Walsh <notifications@github.com> wrote:
> 
> Apologies for the confusion. The fixes are definitely in the repository. My guess is that GitHub is still processing a long backlog of updates. If it's not fixed by tomorrow, or whenever GitHub claims victory, I'll take a closer look.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

====================================================================== 
B. Tommie Usdin                        mailto:btusdin@mulberrytech.com
Mulberry Technologies, Inc.               https://www.mulberrytech.com
17 West Jefferson Street                           Phone: 301/315-9631 
Suite 207                                    Direct Line: 301/315-9634 
Rockville, MD  20850                                 Fax: 301/315-8285 
----------------------------------------------------------------------
Mulberry Technologies: A Consultancy Specializing in XML and SGML               
======================================================================
